//총 32강.
export const randomArray = [
  { foodName : '순대국', foodImg : 'img/time/mor-lun2.jpg' ,description : '해장의 대가.'},
  { foodName : '샐러드', foodImg : 'img/time/mor-lun1-1.jpg',description : '이번기회에 다이어트 어떠세요?' },
  { foodName : '쌀국수', foodImg : 'img/time/lunch12.jpg' ,description : '향신료 향이 매력적인'},
  { foodName : '김밥', foodImg : 'img/time/mor-lun9.jpg',description : '만만하지만 맛있는!' },
  { foodName : '빵', foodImg : 'img/time/morning1.jpg',description : '커피랑 먹으면 은근 든든!' },
  { foodName : '전복죽', foodImg : 'img/time/morning2.jpg' ,description : '어디 아프세요?ㅠ0ㅠ'},
  { foodName : '낙지볶음', foodImg : 'img/time/lun-din1.jpg' ,description : '기운 철철 보양식!'},
  { foodName : '치즈돈까스', foodImg : 'img/time/lun-din2.jpg' ,description : '치즈가 쭈욱~ 초딩입맛에게 최고!'},
  { foodName : '짬뽕', foodImg : 'img/time/lun-din12.jpg',description : '짜장면의 영원한 라이벌.' },
  { foodName : '초밥', foodImg : 'img/time/lun-din3.jpg' ,description : '말이 필요없는'},
  { foodName : '피자', foodImg : 'img/time/lun-din4.jpg' ,description : '언제먹어도 맛잇쥬~!'},
  { foodName : '파스타', foodImg : 'img/time/lun-din6.jpg' ,description : '데이트 단골템.'},
  { foodName : '떡볶이', foodImg : 'img/time/lunch1-1.jpg' ,description : '맵싹~한 국민간식'},
  { foodName : '치킨', foodImg : 'img/time/dinner1-3.jpg' ,description:'맥주가 필요하다.'},
  { foodName : '덮밥', foodImg : 'img/time/lunch2.jpg',description : '샥샥 비벼먹으면 제맛!' },
  { foodName : '꼬막비빔밥', foodImg : 'img/time/lunch3.jpg' ,description : '입안가득 꼬막의 향~ 냠냠 굿~'},
  { foodName : '햄버거', foodImg : 'img/time/lunch4-2.jpg',description : '패스트푸드만큼 만만한게 없지!' },
  { foodName : '샌드위치', foodImg : 'img/time/morning4.jpg',description : '이번기회에 다이어트 어떠세요?' },
  { foodName : '된장찌개', foodImg : 'img/time/morning8.jpg',description : '엄마 단골템' },
  { foodName : '삼겹살', foodImg : 'img/time/dinner5-2.jpg',description : '만만한 주제에 맛있는' },
  { foodName : '족발', foodImg : 'img/time/dinner7.jpg',description : '콜라겐 풍부한' },
  { foodName : '회', foodImg : 'img/time/dinner2.jpg',description : '소주가 생각나는' },
  { foodName : '곱창', foodImg : 'img/time/dinner4-1.jpg' ,description:'돼지런해지고 싶다. 볶음밥도 추가요~'},
  { foodName : '양고기', foodImg : 'img/time/dinner9.jpg',description : '중독적인 향!' },
  { foodName : '칼국수', foodImg : 'img/time/lunch9.jpg',description : '해물/들깨/매운 맛도 다양한' },
  { foodName : '만두', foodImg : 'img/time/snack5.jpg' ,description : '하나씩 집어먹으면 어느새 순삭.'},
  { foodName : '파전', foodImg : 'img/time/snack6.jpg' ,description : '비오는날의 디폴트값 메뉴.'},
  { foodName : '김치볶음밥', foodImg : 'img/time/lunch6.jpg',description : '만만하지만 언제먹어도 맛있는!' },
  { foodName : '라면', foodImg : 'img/time/lunch7-3.jpg' ,description : '둘리도 좋아하는'},
  { foodName : '육개장', foodImg : 'img/time/lunch8.jpg' ,description : '속 쉬원~한~'},
  { foodName : '팟타이', foodImg : 'img/time/lunch10.jpg' ,description : '태국음식 사랑해요!'},
  { foodName : '짜장면', foodImg : 'img/time/lun-din11.jpg',description : '어머니는 분명 좋아하심 ' },

  { foodName : '그렇게 못고르시겠어요?', foodImg : 'img/time/healty.jpg',description : '당신을 진정한 결정장애로 임명합니다.' },
  { foodName : '낙곱새', foodImg : 'img/time/dinner10.jpg',description : '밥도둑 신흥강자.' },
  { foodName : '양념치킨', foodImg : 'img/time/dinner1-1.jpg' ,description : '맥주가 필요하다.'},
  { foodName : '와플', foodImg : 'img/time/snack9.jpg',description : '와플대학 장학생이 되보세요. ' },
  { foodName : '카레', foodImg : 'img/time/lunch13.jpg' ,description : '은근 맛있지 않나요??'},
  { foodName : '부리또', foodImg : 'img/withWho/alone7.jpg',description : '간단히 먹기 좋은' },
  { foodName : '컵라면', foodImg : 'img/withWho/alone8.jpg' ,description : '만만하게 한끼 때우기 좋은,' },
  { foodName : '요거트시리얼', foodImg : 'img/withWho/alone10.jpg' ,description : '아침에 먹기 좋은' },
  { foodName : '마라롱샤', foodImg : 'img/withWho/ff1.jpg' ,description : '솔직히 맛있는데 파는데 찾기어려운,' },
  { foodName : '꿔바로우', foodImg : 'img/withWho/ff3.jpeg' ,description : '바삭쫄깃' },
  { foodName : '마라탕', foodImg : 'img/withWho/ff4.jpg',description : '마라 매니아라면,'  },
  { foodName : '꼬치', foodImg : 'img/withWho/ff6.jpg',description : '한사람 당 10개 가능한.'  },
  { foodName : '나베', foodImg : 'img/withWho/ff9.jpg',description : '집들이 단골템' },
  { foodName : '감바스', foodImg : 'img/withWho/date1.jpg' ,description : '와인과 함께 어떠세요?'},
  { foodName : '분짜', foodImg : 'img/withWho/date2.jpg',description : '쌀국수만큼 맛있는' },
  { foodName : '랍스터', foodImg : 'img/withWho/date12.jpg',description : '돈값하는, ' },
  { foodName : '조개구이', foodImg : 'img/withWho/date13.jpg' ,description : '말이필요합니까. 라면도 추가해서 드세요.'},
  { foodName : '과일', foodImg : 'img/withWho/alone2.jpg' ,description : '꽝이나 마찬가지. 이건 간식입니다.'},
]
export const foodArray =[
  { foodName : '순대국', foodImg : 'img/time/mor-lun2.jpg' ,description : '해장의 대가.'},
  { foodName : '샐러드', foodImg : 'img/time/mor-lun1-1.jpg',description : '이번기회에 다이어트 어떠세요?' },
  { foodName : '쌀국수', foodImg : 'img/time/lunch12.jpg' ,description : '향이 매력적인'},
  { foodName : '김밥', foodImg : 'img/time/mor-lun9.jpg',description : '만만하지만 맛있는!' },
  { foodName : '빵', foodImg : 'img/time/morning1.jpg',description : '커피랑 먹으면 은근 든든!' },
  { foodName : '전복죽', foodImg : 'img/time/morning2.jpg' ,description : '어디 아프세요?ㅠ0ㅠ'},
  { foodName : '낙지볶음', foodImg : 'img/time/lun-din1.jpg' ,description : '기운 철철 보양식!'},
  { foodName : '치즈돈까스', foodImg : 'img/time/lun-din2.jpg' ,description : '치즈가 쭈욱~ 초딩입맛에게 최고!'},
  { foodName : '짬뽕', foodImg : 'img/time/lun-din12.jpg',description : '짜장면의 영원한 라이벌.' },
  { foodName : '초밥', foodImg : 'img/time/lun-din3.jpg' ,description : '말이 필요없는'},

  { foodName : '피자', foodImg : 'img/time/lun-din4.jpg' ,description : '언제먹어도 맛잇쥬~!'},
  { foodName : '파스타', foodImg : 'img/time/lun-din6.jpg' ,description : '데이트 단골템.'},
  { foodName : '떡볶이', foodImg : 'img/time/lunch1-1.jpg' ,description : '맵싹~한 국민간식'},
  { foodName : '치킨', foodImg : 'img/time/dinner1-3.jpg' ,description:'맥주가 필요하다.'},
  { foodName : '덮밥', foodImg : 'img/time/lunch2.jpg',description : '샥샥 비벼먹으면 제맛!' },
  { foodName : '꼬막비빔밥', foodImg : 'img/time/lunch3.jpg' ,description : '입안가득 꼬막의 향~ 냠냠 굿~'},
  { foodName : '햄버거', foodImg : 'img/time/lunch4-2.jpg',description : '패스트푸드만큼 만만한게 없지!' },
  { foodName : '샌드위치', foodImg : 'img/time/morning4.jpg',description : '이번기회에 다이어트 어떠세요?' },
  { foodName : '된장찌개', foodImg : 'img/time/morning8.jpg',description : '엄마 단골템' },
  { foodName : '삼겹살', foodImg : 'img/time/dinner5-2.jpg',description : '만만한 주제에 맛있는' },

  { foodName : '족발', foodImg : 'img/time/dinner7.jpg',description : '콜라겐 가득~ 족발먹고 꿀피부되세요.' },
  { foodName : '회', foodImg : 'img/time/dinner2.jpg',description : '소주가 생각나는' },
  { foodName : '곱창', foodImg : 'img/time/dinner4-1.jpg' ,description:'돼지런해지고 싶다. 볶음밥도 추가요~'},
  { foodName : '부리또', foodImg : 'img/withWho/alone7.jpg',description : '간단히 먹기 좋은' },
  { foodName : '칼국수', foodImg : 'img/time/lunch9.jpg',description : '해물/들깨/매운 맛도 다양한' },
  { foodName : '와플', foodImg : 'img/time/snack9.jpg',description : '와플대학 장학생이 되보세요. ' },
  { foodName : '파전', foodImg : 'img/time/snack6.jpg' ,description : '비오는날의 디폴트값 메뉴.'},
  { foodName : '김치볶음밥', foodImg : 'img/time/lunch6.jpg',description : '만만하지만 언제먹어도 맛있는!' },
  { foodName : '라면', foodImg : 'img/time/lunch7-3.jpg' ,description : '둘리도 좋아하는'},
  { foodName : '육개장', foodImg : 'img/time/lunch8.jpg' ,description : '속 쉬원~한~'},
  { foodName : '팟타이', foodImg : 'img/time/lunch10.jpg' ,description : '태국음식 사랑해요!'},
  { foodName : '짜장면', foodImg : 'img/time/lun-din11.jpg',description : '어머니는 분명 좋아하심 ' }
]
